export const API_URL = 'https://tindhair-api.christianabdelmassih.com/api';
//export const API_URL = 'http://localhost:3000/api';

export const START_SCREEN = 'Splash';
//export const START_SCREEN = 'LoginSelection';

export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const LIKE_TRY = 'LIKE_TRY'
export const LIKE_FAIL = 'LIKE_FAIL'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'

export const FETCH_LIKED_HAIRSTYLES_TRY = 'FETCH_LIKED_HAIRSTYLES_TRY'
export const FETCH_LIKED_HAIRSTYLES_SUCCESS = 'FETCH_LIKED_HAIRSTYLES_SUCCESS'
export const FETCH_LIKED_HAIRSTYLES_FAIL = 'FETCH_LIKED_HAIRSTYLES_FAIL'

export const NEXT_HAIRSTYLE = 'NEXT_HAIRSTYLE'
export const FETCH_HAIRSTYLES_TRY = 'FETCH_HAIRSTYLES_TRY'
export const FETCH_HAIRSTYLES_SUCCESS = 'FETCH_HAIRSTYLES_SUCCESS'
export const FETCH_HAIRSTYLES_FAIL = 'FETCH_HAIRSTYLES_FAIL'

export const LOGIN_TRY = 'LOGIN_TRY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const STORE_REFRESH_TOKEN = 'STORE_REFRESH_TOKEN';
export const STORE_ACCESS_TOKEN = 'STORE_ACCESS_TOKEN';
export const CLEAR_STORE = 'CLEAR_STORE';

export const STORE_SIGNUP_DETAILS = 'STORE_SIGNUP_DETAILS';
export const SIGNUP_TRY = 'SIGNUP_TRY';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const NULLIFY_MESSAGE = 'NULLIFY_MESSAGE';

export const HIGHLIGHT_LOG_IN = 'HIGHLIGHT_LOG_IN';
