export const API_URL = 'https://tindhair-api.christianabdelmassih.com/api';
//export const API_URL = 'http://localhost:3000/api';

export const START_SCREEN = 'Splash';
//export const START_SCREEN = 'LoginSelection';

export const STORE_ME = 'STORE_ME';

export const RESET_TAB = 'RESET_TAB';

export const LOGOUT_TRY = 'LOGOUT_TRY';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const NOT_LOGGED_IN = 'NOT_LOGGED_IN';

export const UPDATE_INDEX_TRY = 'UPDATE_INDEX_TRY';
export const UPDATE_INDEX_SUCCESS = 'UPDATE_INDEX_SUCCESS';

export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS';
export const REMOVE_LIKE_TRY = 'REMOVE_LIKE_TRY';
export const REMOVE_LIKE_FAIL = 'REMOVE_LIKE_FAIL';

export const DELETE_HAIRSTYLE_SUCCESS = 'DELETE_HAIRSTYLE_SUCCESS';
export const DELETE_HAIRSTYLE_TRY = 'DELETE_HAIRSTYLE_TRY';
export const DELETE_HAIRSTYLE_FAIL = 'DELETE_HAIRSTYLE_FAIL';

export const CHANGE_GENDER_TRY = 'CHANGE_GENDER_TRY';
export const CHANGE_GENDER_SUCCESS = 'CHANGE_GENDER_SUCCESS';
export const CHANGE_GENDER_FAIL = 'CHANGE_GENDER_FAIL';

export const LIKE_TRY = 'LIKE_TRY'
export const LIKE_FAIL = 'LIKE_FAIL'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'

export const DELETE_ACCOUNT_TRY = 'DELETE_ACCOUNT_TRY';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

export const FETCH_MY_HAIRSTYLES_SUCCESS = 'FETCH_MY_HAIRSTYLES_SUCCESS'
export const FETCH_MY_HAIRSTYLES_TRY = 'FETCH_MY_HAIRSTYLES_TRY'
export const FETCH_MY_HAIRSTYLES_FAIL = 'FETCH_MY_HAIRSTYLES_FAIL'

export const SEND_HAIRSTYLE_SUCCESS = 'SEND_HAIRSTYLE_SUCCESS';
export const SEND_HAIRSTYLE_TRY = 'SEND_HAIRSTYLE_TRY';
export const SEND_HAIRSTYLE_FAIL = 'SEND_HAIRSTYLE_FAIL';

export const FETCH_LIKED_HAIRSTYLES_TRY = 'FETCH_LIKED_HAIRSTYLES_TRY'
export const FETCH_LIKED_HAIRSTYLES_SUCCESS = 'FETCH_LIKED_HAIRSTYLES_SUCCESS'
export const FETCH_LIKED_HAIRSTYLES_FAIL = 'FETCH_LIKED_HAIRSTYLES_FAIL'

export const NEXT_HAIRSTYLE = 'NEXT_HAIRSTYLE'
export const FETCH_HAIRSTYLES_TRY = 'FETCH_HAIRSTYLES_TRY'
export const FETCH_HAIRSTYLES_SUCCESS = 'FETCH_HAIRSTYLES_SUCCESS'
export const FETCH_HAIRSTYLES_FAIL = 'FETCH_HAIRSTYLES_FAIL'

export const LOGIN_TRY = 'LOGIN_TRY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const STORE_REFRESH_TOKEN = 'STORE_REFRESH_TOKEN';
export const STORE_ACCESS_TOKEN = 'STORE_ACCESS_TOKEN';
export const CLEAR_STORE = 'CLEAR_STORE';
export const CLEAR_TOKENS = 'CLEAR_TOKENS';

export const STORE_SIGNUP_DETAILS = 'STORE_SIGNUP_DETAILS';
export const SIGNUP_TRY = 'SIGNUP_TRY';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const NULLIFY_MESSAGE = 'NULLIFY_MESSAGE';

export const HIGHLIGHT_LOG_IN = 'HIGHLIGHT_LOG_IN';
